# Generated by Django 5.1.7 on 2025-03-20 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('barcode', models.CharField(max_length=50)),
                ('fssai_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FoodIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_rank', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scan.food')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scan.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('quantity_unit', models.CharField(max_length=50)),
                ('energy', models.FloatField()),
                ('carbohydrate', models.FloatField()),
                ('total_sugar', models.FloatField(default=None)),
                ('added_sugar', models.FloatField(default=None)),
                ('total_fat', models.FloatField()),
                ('saturated_fat', models.FloatField(default=None)),
                ('trans_fat', models.FloatField(default=None)),
                ('protein', models.FloatField()),
                ('fibre', models.FloatField(default=None)),
                ('sodium', models.FloatField(default=None)),
                ('cholesterol', models.FloatField(default=None)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scan.food')),
            ],
        ),
    ]
