# Generated by Django 5.1.7 on 2025-03-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NutritionalDetails',
            new_name='NutritionalDetail',
        ),
    ]
