# Generated by Django 5.1.7 on 2025-04-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
