# Generated by Django 5.1.7 on 2025-04-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0004_ingredient_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionaldetail',
            name='ingredient_list',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
    ]
